// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lehudiyeqdvpscdggcai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlaHVkaXllcWR2cHNjZGdnY2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzUxMjEsImV4cCI6MjA3MjMxMTEyMX0.ybS3kH74pGee-Ypy5mivRdEjzo_fDu2KtBGmZrmr_Y8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});